<!DOCTYPE html>
<!-- saved from url=(0045)http://cleancutworld.com/support/privacy.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>Privacy and Support</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{asset('dist/css')}}/bootstrap.min.css">
</head>
<body>
  
<div class="container">
<h2>Terms of Use</h2>
<p>We’ve tried to make our Terms of Use and Privacy Policy (collectively, the “Terms”) as simple and straightforward as possible, but please read them carefully. The Terms exist to keep Joinn fun and safe. Please be respectful of others. We want you to be able to communicate and express yourselves freely and creatively!</p>
<p>The Terms govern and apply to your access and use of Joinn App and other websites operated by Joinn Mobile Inc Pte. Ltd. (“Joinn”, “we” or “us”) on which a link to the Terms is posted (“Site”) and Joinn’s mobile apps in which the Terms are made available (collectively, “Apps”). The Site and the Apps are collectively referred to as the “Service.”</p>
<p>PLEASE READ THE FOLLOWING TERMS CAREFULLY. BY CLICKING “SIGN UP” ON THE SITE OR BY DOWNLOADING, INSTALLING OR OTHERWISE ACCESSING OR USING THE APP(S) OR THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE FOLLOWING TERMS, INCLUDING THE PRIVACY POLICY. By accessing or using our Service, you agree to be bound by all of the terms and conditions described in the Terms. If you are not eligible or do not agree to all of the Terms, do not use our Service.</p>
<h2>You acknowledge and agree to the following:</h2>
<p>The App(s) are licensed, not sold to you, and you may use the Service only as set forth in the Terms;</p>
<p>When you first create an account on the Service, we may ask for your mobile number in order to verify your account by text message and any applicable text messaging fees of your mobile network operator (the “Carrier”) will apply;</p>
<p>Your use of the Service may be subject to separate third party terms of service and fees, including without limitation the terms of service and data, SMS, MMS, and other fees of the Carrier, which are your sole responsibility;</p>
<p>The Service is provided “as is” without warranties of any kind and Joinn’s liability to you is limited; and</p>
<p>Disputes arising hereunder will be resolved by binding arbitration. Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge. Please review the Dispute Resolution and Arbitration provision below for the details regarding your agreement to arbitrate any disputes with Joinn.</p>
<h2>USE OF THE SERVICE</h2>
<p>Subject to the Terms (including without limitation your compliance with the Terms), you have the limited, non-exclusive, non-transferable, non-sub licensable, revocable right to download and install a copy of the App(s) from a legitimate marketplace (such as Apple’s App Store or Google Play) to your mobile device, and to access and use the Service, in each case, for your own personal use.</p>
<p>You may not: (i) copy, modify, or create derivative works of the Service (or any part thereof) for any purpose; (ii) distribute, publicly display, publicly perform, transfer, sell, sublicense, lease, lend, rent or otherwise make available the Service (or any part thereof) to any third party; (iii) decompile, reverse-engineer, disassemble or interfere with or circumvent the Service (or any part thereof), including without limitation any security or access control mechanism (except to the extent such a restriction is impermissible under applicable law); or (iv) use the Service (or any part thereof) in any unlawful manner, for any unlawful purpose, or in any manner inconsistent with the Terms.</p>
<p>Our Service may change from time to time and/or we may stop (permanently or temporarily) providing the Service (or features within the Service), possibly without prior notice to you. Our Service may include advertisements, which may be targeted to the content or information on the Service, queries made through the Service, or from other information. The types and extent of advertising on the Service are also subject to change over time. In consideration for providing you the Service, you agree that we and our third party providers and partners may place advertising, including Ad choices, on our Service or in connection with the display of content or information on our Service. If you want to put your advertisement on the Service, please refer to Advertising Policy, which governs and applies to your access and use of our Service as advertising purpose.</p>
<p>Certain features of our Service may be subject to additional terms or conditions, which will be posted with those features. Such terms and conditions are incorporated by reference into the Terms.</p>
<p>In order to download the App, you may be required by third parties who are providing services in connection with the App, such as Apple, Inc. or Google (each, a “Service Provider”) to create an account. You are solely responsible for maintaining the security of any logins, passwords, or other credentials that you select or that are provided to you to access your account with any Service Provider. Your access and use of any account with a Service Provider, including without limitation in connection with the Service, is subject to any terms, conditions, and policies, including privacy policies, of that Service Provider. Joinn is not responsible for any act or omission of any Service Provider. Joinn does not provide you with the equipment to access or use the Service. You are responsible for all fees charged by third parties to access and use the Service (e.g., charges by Carriers). Without limiting the foregoing, you are solely responsible for the payment of all applicable fees associated with any Carrier service plan you use in connection with your access and use of the Service (such as voice, data, SMS, MMS, roaming, and other applicable fees charged by the Carrier). Accordingly, you should use care in selecting a service plan offered by your Carrier. If your device is lost or stolen, you must change the password or notify Joinn immediately to prevent illegitimate use.</p>
<h2>CREATING AN ACCOUNT</h2>
<p>In order to access and use the Service, you may need to register and create an account (your “Account”). By creating an Account, you represent that you are of legal age to form a binding contract, have not previously been suspended or removed from the Service and are not a person barred from receiving the Service under the laws of the Singapore or other applicable jurisdiction.</p>
<p>When creating an Account, you may be required to provide your email address and mobile number in order to verify your Account by text message. Please be aware that your Carrier’s text messaging fees may apply for mobile number verification. When creating an Account, you also may be required to provide certain personal information about yourself and will establish a username, a ID and a password. We reserve the right to remove or reclaim a username or a ID if we believe it is appropriate, for example, if your username or ID suggests that you are a person other than yourself.</p>
<p>You agree to provide and maintain accurate, current and complete information about your Account, including without limitation your mobile phone number. Without limiting the foregoing, in the event you change or deactivate your mobile phone number, you will update your Account information promptly to ensure that your messages are not sent to the person who acquires your old number.</p>
<h2>When creating an Account, don’t:</h2>
<p>Provide any false personal information to us (including without limitation a false username or ID) or create any Account for anyone other than yourself without such other person’s permission;</p>
<p>Use a username or a ID that is the name of another person with the intent to impersonate that person;</p>
<p>Use a username or a ID that is subject to rights of another person without appropriate authorization; or</p>
<p>Use a username or a ID that is offensive, vulgar or obscene or otherwise in bad taste.</p>
<p>We reserve the right to suspend or terminate your Account if any information provided during the registration process or thereafter proves to be inaccurate, false or misleading, or to reclaim any username or ID that you create through the Service that violates our Terms. You are responsible for maintaining the confidentiality of your password and Account, and agree to notify us if your password is lost, stolen, or disclosed to an unauthorized third party, or otherwise may have been compromised. You are responsible for activities that occur under your Account. If you have reason to believe that your Account (including without limitation your mobile phone) is no longer secure, then you must immediately notify us at <a href="mailto:joinnapp@outlook.com">joinnapp@outlook.com.</a></p>
<p>You can link your Account to various webmail, social networking, and other online accounts. You may only link your own accounts. We will access and retrieve your account information from these sites on your behalf (in some cases, by using your username, ID and password) to make certain information or services available to you through the Service. By linking your other accounts, you expressly authorize us to access your account information from those third party accounts, on your behalf as your agent and permit us to access, use and, in some cases, store your account information to accomplish the foregoing.</p>
<h2>PAYMENT</h2>
<p>Access to the Service, or to certain features of the Service, may require you to pay fees to a Service Provider. If you have any questions or issues with such payments, please contact the applicable Service Provider.</p>
<h2>PRIVACY POLICY</h2>
<p>Please refer to our Privacy Policy for information on how we collect, use and disclose information from our users. The Privacy Policy is incorporated by reference into these Terms.</p>
<h2>CONTENT SUBMISSIONS</h2>
<p>Our Service allows you and other users to post, link, store, share and otherwise make available certain information, images, videos, text and/or other content (“Content”). You are responsible for the Content that you make available to the Service, including without limitation its legality, reliability, and appropriateness. You retain any and all of your ownership rights to any Content you make available on or through the Service and you are responsible for protecting those rights.</p>
<p>You can remove Content that you posted by specifically deleting it. In certain instances, however, some Content (such as posts or comments you make) may not be completely removed on the Service and copies of your Content may continue to exist on the Service and/or elsewhere. We are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any Content on the Service.</p>
<p>You also have the option permanently deleting your Account by visiting your Account settings in most Apps. If an App does not have Account settings, you can contact us to temporarily disable or permanently delete your Account. For some Apps, you may only have the option of permanently </p>
<p>deleting your Account. If you delete your Account, we will permanently delete your Account information and Content, and we will delete your messages according to our regular retention schedule. Please note that we will continue to store certain information (including without limitation your Content) for analytics purposes, but that information will not include your personal information such as name, email address, or telephone number. We will also retain any information (including without limitation your Content) as required by law. Comments or emotions you make on Content shared by others, or messages you send, may also remain visible to other users after you delete your Account.</p>
<p>You represent and warrant that: (i) the Content is yours (you own it) or you have the right to use it and to grant us the right and license granted in the Terms, and (ii) the posting of your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person.</p>
<p>We ask that you respect our on-line community and other users when posting Content and using the Service. You agree not to:</p>
<p>Submit material that violates a third party’s proprietary rights, including without limitation privacy and publicity rights, or that otherwise violates any applicable law;</p>
<p>Publish falsehoods or misrepresentations that could damage us, our users or any third party;</p>
<p>Publish any private information of someone, like their address, phone number, email address, and similar information without their permission;</p>
<p>Submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate;</p>
<p>Post advertisements without prior consent or contract with us ;</p>
<p>Impersonate another person or represent yourself as affiliated with us, our staff or other industry professionals, including without limitation by use of our trademarks, service marks, logos, branding or names without express written authorization from us;</p>
<p>Solicit a user’s password or other account information; or</p>
<p>Harvest user names, addresses, or email addresses for any purpose.</p>
<p>This list is an example and is not intended to be complete or exclusive. We don’t have an obligation to monitor your access to or use of the Service or to review or edit any Content, but we have the right to do so for the purpose of operating the Service, to ensure your compliance with the Terms, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. We reserve the right, at any time and without prior notice, to remove or disable access to any Content that we consider, in our sole discretion, to be in violation of the Terms or otherwise harmful to the Service.</p>
<p>Since the Service may not always be available and your Content on the Service may not always be available, you agree not to rely on the Service for the purposes of Content access, storage or backup. Joinn will not be liable to you for any modifications, suspension or discontinuation of the Service or the loss of any Content.</p>
<h2>CONTENT ON THE SERVICE</h2>
<p>The Content available through the Service has not been reviewed, verified or authenticated by us, and may include inaccuracies or false information or be offensive, indecent or objectionable. We make no representations, warranties, or guarantees in connection with our Service or any Content on the Service, including relating to the quality, suitability, truth, accuracy or completeness of any content contained in the Service. You acknowledge sole responsibility for and assume all risk arising from your use or reliance of any Content. If notified by a user or content owner that Content allegedly does not conform to the Terms, we may investigate the allegation and determine in our sole discretion whether to remove the Content, which we reserve the right to do at any time and without notice.</p>
<h2>COPYRIGHT POLICY</h2>
<p>We do not permit copyright infringing activities and infringement of intellectual property rights on the Service and will remove any such Content if properly notified that such Content infringes on another’s intellectual property rights. If you are a copyright owner or an agent thereof and believe that any Content infringes upon your copyrights, you may submit a notification by providing our Copyright Agent with the following information in writing:</p>
<p>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright’s interest;</p>
<p>A description of the copyrighted work that you claim has been infringed;</p>
<p>A description of the material that you claim is infringing and where it is located on the Service;</p>
<p>Identification of the URL or other specific location on the Service where the material that you claim is infringing is located;</p>
<p>Your address, telephone number, and email address;</p>
<p>A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</p>
<p>A statement by you, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.</p>
<p>You can contact our Copyright Agent via email at <a href="mailto:joinnapp@outlook.com">joinnapp@outlook.com.</a></p>
<p>Joinn will promptly terminate the Accounts of users that are determined by Joinn to be “repeat infringers." A repeat infringer is a user who has repeatedly been notified of infringing activity and/or has had Content repeatedly removed from the Service.</p>
<h2>UNAUTHORIZED ACTIVITIES</h2>
<p>Our Service may be used and accessed for lawful purposes only. You agree that you will not do any of the following while using or accessing the Service: (i) attempt to access or search the Service or download Content from the Service through the use of any engine, software, tool, agent, device or mechanism (including without limitation spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by us or other generally available third party web browsers; (ii) access, tamper with, interfere or use non-public areas of the Service, our computer systems, or the technical delivery systems of our providers, including without limitation by uploading or otherwise disseminating viruses, adware, spyware, worms, or other malicious code; (iii) gather and use information, such as other users’ names, real names, email addresses, available through the Service to transmit any unsolicited advertising, junk mail, spam or other form of solicitation; (iv) use the Service for any commercial purpose or for the benefit of any third party or in any manner not permitted by the Terms; (v) violate any applicable law or regulation; or (vi) encourage or enable any other individual to do any of the foregoing; or (vii) interfere with any user’s enjoyment of the Service, including without limitation by (a) making unsolicited offers or advertisements to other users of the Service or (b) attempting to collect, personal information about users or third parties without their consent. We reserve the right to investigate and prosecute violations of any of the above and/or involve and cooperate with law enforcement authorities in prosecuting users who violate the Terms</p>
<h2>INDEMNITY</h2>
<p>You agree to indemnify and hold us and our officers, directors, employees, consultants, affiliates, subsidiaries and agents harmless from and against any and all claims, costs, damages, liabilities, and expenses (including without limitation attorneys’ fees) we incur in relation to or arising from (i) your access to or use of the Service, (ii) your violation of the Terms or any applicable law or regulation, (iii) your violation of any rights of any third party, including without limitation intellectual property rights or rights of publicity, confidentiality, property or privacy; or (iv) any disputes or issues between you and any third party. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (and without limiting your indemnification obligations with respect to such matter), and in such case, you agree to cooperate with our defense of such claim.</p>
<h2>LINKS TO THIRD PARTY SITES</h2>
<p>The Service may include links to other sites and services that are not operated by us. We are providing these links to you only as a convenience and are not responsible for the content or links displayed on such sites. You are responsible for and assume all risk arising from your use or reliance of any third party sites. Joinn may provide tools through the Service that enable you to export information, including without limitation Content, to third party services. By using these tools, you agree that we may transfer such information to the applicable third-party service. Such third party services are not under our control, and we are not responsible for their use of your exported information.</p>
<h2>CHANGES TO THE TERMS</h2>
<p>We reserve the right, at our discretion, to change the Terms on a going-forward basis at any time. Please check the Terms periodically for changes. In the event that a change to the Terms materially modifies your rights or obligations, we will make reasonable efforts to notify you of such change. We may provide notice through a pop-up or banner within the Service, by sending an email to any address you may have used to register for an Account, or through other similar mechanisms. Additionally, if the changed Terms materially modify your rights or obligations, we may require you to provide consent by accepting the changed Terms. If we require your acceptance of the changed Terms, changes are effective only after your acceptance. If you do not accept the changed Terms, we may terminate your access to and use of the Service. All other changes are effective upon publication of the changed Terms. Disputes arising under the Terms will be resolved in accordance with the Terms in effect at the time the dispute arose.</p>
<h2>OWNERSHIP</h2>
<p>Our Service (including without limitation the App(s)) is protected by copyright, trademark, and other laws of the United States and foreign countries including Singapore. Except as expressly provided in the Terms, we (or our licensors) exclusively own all right, title and interest in and to the Service (including without limitation the App(s)), including all associated intellectual property rights. Except as expressly provided in the Terms, you may not make use of the Service, and Joinn reserves all rights to the Service. You may not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Service (including without limitation the App(s)). You acknowledge and agree that any feedback, comments or suggestions you may provide regarding the Service (including without limitation the App(s)) (“Feedback”) will be the sole and exclusive property of Joinn and you hereby irrevocably assign to us all of your right, title and interest in and to all Feedback.</p>
<h2>TERMINATION</h2>
<P>If you breach any of the provisions of the Terms, your permission to use the Service will terminate automatically. Additionally, we have the right in our sole discretion to suspend or disable your access to or use of the App(s) and/or Service or to terminate your Account and the Terms at any time, with or without notice. You may terminate the Terms at any time, with or without notice, by deleting your Account and discontinuing all access to and use of the Service. If you or we terminate or delete your Account or terminate the Terms, you will promptly remove all copies of the App and parts thereof from your possession and control. Upon termination of the Terms, any provision that by its nature or express terms should survive will survive such termination or expiration, including, but not limited to, this sentence and the following provisions: the last paragraph of “Use of the Service,” as well as “Payment,” “Privacy Policy” (for information provided during the duration of the Terms), the license you grant in “Content Submissions,” “Copyright Policy,” “Indemnity,” “Links to Third Party Sites,” “Ownership,” “Limitation of Liability,” “Exclusions,” “General,” “Dispute Resolution and Arbitration.”</P>
<h2>DISCLAIMER</h2>
<p>YOU UNDERSTAND AND AGREE THAT SERVICE (INCLUDING WITHOUT LIMITATION ANY CONTENT OR MATERIALS OFFERED THROUGH THE SERVICE) ARE PROVIDED TO YOU “AS IS” AND ON AN “AS AVAILABLE” BASIS. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. WE MAKE NO WARRANTY THAT THE SERVICE (INCLUDING WITHOUT LIMITATION ANY CONTENT OR MATERIALS OFFERED THROUGH THE SERVICE)</p>
<!-- end -->
</body>
</html>